name: Release Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  release:
    name: Bump version and tag it
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create Git Tag from package.json version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "Version: $VERSION"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "v$VERSION"
          git push origin "v$VERSION"
